import { theme } from "antd";

const { darkAlgorithm } = theme;

export const antdTheme = {
    algorithm: darkAlgorithm,
    token: {
        // Primary colors
        colorPrimary: "#ff6b35",
        colorSuccess: "#52c41a",
        colorError: "#ff4d4f",
        colorWarning: "#ff8c42",
        colorInfo: "#1890ff",

        // Text colors
        colorText: "#e0e0e0",
        colorTextSecondary: "#b0b0b0",
        colorTextTertiary: "#8a8a8a",
        colorTextQuaternary: "#6a6a6a",

        // Background colors
        colorBgContainer: "#242424",
        colorBgElevated: "#2a2a2a",
        colorBgLayout: "#1a1a1a",
        colorBgSpotlight: "#3a3a3a",
        colorBgMask: "rgba(0, 0, 0, 0.85)",

        // Border colors
        colorBorder: "#3a3a3a",
        colorBorderSecondary: "#2a2a2a",

        // Typography
        fontSize: 14,
        fontSizeHeading1: 28,
        fontSizeHeading2: 24,
        fontSizeHeading3: 20,
        fontFamily:
            "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",

        // Layout
        borderRadius: 8,
        borderRadiusLG: 12,
        borderRadiusSM: 4,

        // Control dimensions
        controlHeight: 36,
        controlHeightLG: 40,
        controlHeightSM: 32,

        // Spacing
        paddingXS: 8,
        paddingSM: 12,
        padding: 16,
        paddingLG: 24,
        paddingXL: 32,

        marginXS: 8,
        marginSM: 12,
        margin: 16,
        marginLG: 24,
        marginXL: 32,

        // Shadows
        boxShadow: "0 2px 8px rgba(0, 0, 0, 0.4)",
        boxShadowSecondary: "0 4px 12px rgba(0, 0, 0, 0.6)",
    },
    components: {
        Layout: {
            siderBg: "#0f0f0f",
            headerBg: "#1a1a1a",
            bodyBg: "#1a1a1a",
            footerBg: "#0f0f0f",
            triggerBg: "#ff6b35",
            triggerColor: "#fff",
            lightSiderBg: "#0f0f0f",
            lightTriggerBg: "#ff6b35",
            lightTriggerColor: "#fff",
        },
        Card: {
            colorBgContainer: "#242424",
            colorBorderSecondary: "#3a3a3a",
            borderRadiusLG: 12,
            boxShadow: "0 4px 12px rgba(0, 0, 0, 0.4)",
            paddingLG: 24,
        },
        Button: {
            borderRadius: 6,
            primaryColor: "#fff",
            primaryShadow: "0 2px 8px rgba(255, 107, 53, 0.3)",
            defaultBg: "#2a2a2a",
            defaultBorderColor: "#3a3a3a",
            defaultColor: "#e0e0e0",
            colorPrimaryHover: "#ff8c42",
            colorPrimaryActive: "#ff5722",
        },
        Table: {
            colorBgContainer: "#242424",
            headerBg: "#1a1a1a",
            headerColor: "#ff6b35",
            rowHoverBg: "#2a2a2a",
            borderColor: "#3a3a3a",
            headerBorderRadius: 8,
        },
        Menu: {
            itemBg: "#0f0f0f",
            subMenuItemBg: "#1a1a1a",
            itemSelectedBg: "#ff6b35",
            itemSelectedColor: "#fff",
            itemHoverBg: "#2a2a2a",
            itemColor: "#b0b0b0",
            itemHoverColor: "#ff6b35",
            itemActiveBg: "#ff6b35",
            darkItemBg: "#0f0f0f",
            darkSubMenuItemBg: "#1a1a1a",
            darkItemSelectedBg: "#ff6b35",
            darkItemSelectedColor: "#fff",
            darkItemHoverBg: "#2a2a2a",
            darkItemColor: "#b0b0b0",
        },
        Statistic: {
            titleFontSize: 14,
            contentFontSize: 24,
        },
        Progress: {
            defaultColor: "#ff6b35",
            remainingColor: "#2a2a2a",
            circleTextFontSize: "1em",
        },
        Badge: {
            colorError: "#ff4d4f",
            colorWarning: "#ff8c42",
            colorSuccess: "#52c41a",
            dotSize: 8,
            statusSize: 8,
        },
        Tag: {
            defaultBg: "#2a2a2a",
            defaultColor: "#e0e0e0",
        },
        Input: {
            colorBgContainer: "#2a2a2a",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            colorTextPlaceholder: "#6a6a6a",
            hoverBorderColor: "#ff6b35",
            activeBorderColor: "#ff6b35",
            activeShadow: "0 0 0 2px rgba(255, 107, 53, 0.2)",
        },
        Select: {
            colorBgContainer: "#2a2a2a",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            optionSelectedBg: "#ff6b35",
            optionActiveBg: "#3a3a3a",
            optionSelectedColor: "#fff",
        },
        DatePicker: {
            colorBgContainer: "#2a2a2a",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            colorTextPlaceholder: "#6a6a6a",
            hoverBorderColor: "#ff6b35",
            activeBorderColor: "#ff6b35",
        },
        Modal: {
            contentBg: "#242424",
            headerBg: "#1a1a1a",
            footerBg: "#1a1a1a",
            titleColor: "#ff6b35",
            titleFontSize: 18,
        },
        Drawer: {
            colorBgElevated: "#242424",
            colorBgMask: "rgba(0, 0, 0, 0.8)",
        },
        Alert: {
            colorInfoBg: "rgba(24, 144, 255, 0.1)",
            colorInfoBorder: "#1890ff",
            colorWarningBg: "rgba(255, 140, 66, 0.1)",
            colorWarningBorder: "#ff8c42",
            colorErrorBg: "rgba(255, 77, 79, 0.1)",
            colorErrorBorder: "#ff4d4f",
            colorSuccessBg: "rgba(82, 196, 26, 0.1)",
            colorSuccessBorder: "#52c41a",
        },
        Tooltip: {
            colorBgSpotlight: "#3a3a3a",
            colorTextLightSolid: "#e0e0e0",
        },
        Popover: {
            colorBgElevated: "#242424",
            colorText: "#e0e0e0",
        },
        Dropdown: {
            colorBgElevated: "#242424",
            colorText: "#e0e0e0",
            colorPrimaryHover: "#ff6b35",
        },
        Steps: {
            colorPrimary: "#ff6b35",
            colorText: "#b0b0b0",
            colorTextDescription: "#6a6a6a",
            colorFillContent: "#2a2a2a",
        },
        Tabs: {
            colorPrimary: "#ff6b35",
            colorBgContainer: "#1a1a1a",
            colorText: "#b0b0b0",
            colorBorderSecondary: "#3a3a3a",
            itemSelectedColor: "#ff6b35",
            itemHoverColor: "#ff8c42",
        },
        Form: {
            labelColor: "#b0b0b0",
            labelFontSize: 14,
            itemMarginBottom: 24,
        },
        Divider: {
            colorSplit: "#3a3a3a",
        },
        Skeleton: {
            colorFill: "#2a2a2a",
            colorFillContent: "#3a3a3a",
        },
        Spin: {
            colorPrimary: "#ff6b35",
        },
        Result: {
            colorTextHeading: "#e0e0e0",
            colorTextDescription: "#b0b0b0",
            colorIcon: "#ff6b35",
        },
        Empty: {
            colorText: "#6a6a6a",
            colorTextDescription: "#4a4a4a",
        },
        Pagination: {
            colorBgContainer: "#2a2a2a",
            colorText: "#b0b0b0",
            colorTextDisabled: "#4a4a4a",
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
        },
        Breadcrumb: {
            colorText: "#b0b0b0",
            colorTextDescription: "#6a6a6a",
            linkColor: "#ff6b35",
            linkHoverColor: "#ff8c42",
            separatorColor: "#4a4a4a",
        },
        Switch: {
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
            colorTextQuaternary: "#4a4a4a",
        },
        Checkbox: {
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
            colorBorder: "#3a3a3a",
            colorBgContainer: "#2a2a2a",
        },
        Radio: {
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
            colorBorder: "#3a3a3a",
            colorBgContainer: "#2a2a2a",
            buttonSolidCheckedBg: "#ff6b35",
        },
        Rate: {
            colorFillContent: "#3a3a3a",
            colorText: "#ff6b35",
        },
        Slider: {
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
            trackBg: "#ff6b35",
            trackHoverBg: "#ff8c42",
            railBg: "#2a2a2a",
            railHoverBg: "#3a3a3a",
            handleColor: "#ff6b35",
            handleActiveColor: "#ff8c42",
            dotBorderColor: "#3a3a3a",
            dotActiveBorderColor: "#ff6b35",
        },
        Upload: {
            colorBorder: "#3a3a3a",
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
            colorFillAlter: "#2a2a2a",
            colorText: "#b0b0b0",
        },
        Timeline: {
            colorText: "#b0b0b0",
            colorTextDescription: "#6a6a6a",
            dotBorderWidth: 2,
            tailColor: "#3a3a3a",
        },
        Transfer: {
            colorBgContainer: "#242424",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            itemHoverBg: "#2a2a2a",
            itemSelectedHoverBg: "#ff6b35",
        },
        Tree: {
            colorBgContainer: "#242424",
            colorText: "#e0e0e0",
            colorTextDescription: "#b0b0b0",
            nodeHoverBg: "#2a2a2a",
            nodeSelectedBg: "#ff6b35",
        },
        TreeSelect: {
            colorBgContainer: "#2a2a2a",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            nodeHoverBg: "#2a2a2a",
            nodeSelectedBg: "#ff6b35",
        },
        Anchor: {
            colorPrimary: "#ff6b35",
            colorText: "#b0b0b0",
            linkPaddingBlock: 4,
            linkPaddingInlineStart: 16,
        },
        Cascader: {
            colorBgContainer: "#2a2a2a",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            optionSelectedBg: "#ff6b35",
            optionHoverBg: "#3a3a3a",
        },
        Segmented: {
            colorBgLayout: "#2a2a2a",
            colorBgElevated: "#ff6b35",
            colorText: "#b0b0b0",
            colorTextLabel: "#e0e0e0",
        },
        Space: {
            paddingSM: 12,
            padding: 16,
        },
        Typography: {
            colorText: "#e0e0e0",
            colorTextDescription: "#b0b0b0",
            colorTextHeading: "#ff6b35",
            colorLink: "#ff6b35",
            colorLinkHover: "#ff8c42",
            colorLinkActive: "#ff5722",
        },
        FloatButton: {
            colorPrimary: "#ff6b35",
            colorPrimaryHover: "#ff8c42",
            colorBgElevated: "#2a2a2a",
            colorText: "#e0e0e0",
        },
        Calendar: {
            colorBgContainer: "#242424",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            colorTextDisabled: "#4a4a4a",
            colorPrimary: "#ff6b35",
        },
        Carousel: {
            colorBgContainer: "#242424",
            dotWidth: 8,
            dotHeight: 8,
            dotActiveWidth: 24,
        },
        Mentions: {
            colorBgContainer: "#2a2a2a",
            colorBorder: "#3a3a3a",
            colorText: "#e0e0e0",
            colorTextPlaceholder: "#6a6a6a",
            dropdownBg: "#242424",
            itemHoverBg: "#3a3a3a",
        },
        Notification: {
            colorBgElevated: "#242424",
            colorText: "#e0e0e0",
            colorTextHeading: "#ff6b35",
            colorIcon: "#ff6b35",
            colorIconHover: "#ff8c42",
        },
        Message: {
            contentBg: "#242424",
            colorText: "#e0e0e0",
            colorSuccess: "#52c41a",
            colorError: "#ff4d4f",
            colorWarning: "#ff8c42",
            colorInfo: "#1890ff",
        },
    },
};
